/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./**/*.html", "./js/**/*.js"],
  theme: {
    extend: {
      colors: {
        bg: "#fdf6ec",
        card: "#ffffff",
        "card-hover": "#f5ead8",
        "green-dark": "#1c3a0f",
        "green-mid": "#2d5016",
        "green-light": "#3d6b1f",
        "green-pale": "#e8f0d8",
        gold: "#c49a1a",
        "gold-pale": "#f5ead8",
        terracotta: "#2d5016",
        "terra-pale": "#f5ead8",
        sky: "#2d5016",
        "sky-pale": "#f5ead8",
        "text-primary": "#1c3a0f",
        "text-secondary": "#3d5c1f",
        muted: "#6b7c52",
        agro: {
          cream: "#fdf6ec",
          "cream-dark": "#f5ead8",
          tan: "#ede0c8",
          peach: "#f0d5a8",
          green: "#2d5016",
          "green-dark": "#1c3a0f",
          "green-light": "#e8f0d8",
          gold: "#c49a1a",
          "gold-warm": "#8b6410",
          text: "#1c3a0f",
          "text-muted": "#6b7c52",
        },
      },
    },
  },
  plugins: [],
};
